// Verfmachine Data - Alle machines uit vergelijkingslijst
// Testmodellen zijn gemarkeerd met testmodel: true

const machines = [
    // === CHAMELEON ===
    // Mengers
    { id: 1, naam: "iMix M2M PRO", fabrikant: "CHAMELEON", type: "MENGER", prijs: 4281, vermogen: "1.1 kW", spanning: "230 V", frequentie: "50 Hz", afmetingen: "800x860x1100 mm", gewicht: "210 kg", capaciteit: "40 kg", laadhoogte: "540 mm", bedrijfssnelheid: "91-140 RPM", geluidsniveau: "65 dB", schudrichting: "Gyroscopic / Biaxial", veiligheidsvoorzieningen: "Emergency Stop, Sliding door, safe mode, automatic speed control", automatisering: "Automatic", gebruikersinterface: "Control panel / touch", connectiviteit: "WiFi", garantie: "1 Jaar", testmodel: true, afbeelding: "https://s3-eu-west-1.amazonaws.com/devchameleon/web-product/680b502ca4d20.png", documentatie: "https://www.chameleon.ie/viewDetails/iMix%20M2M%20PRO/Gyroscopic_Mixers" },
    { id: 2, naam: "iMix M2M", fabrikant: "CHAMELEON", type: "MENGER", prijs: 3665, vermogen: "1.1 kW", spanning: "230 V", frequentie: "50 Hz", afmetingen: "800x860x1100 mm", gewicht: "210 kg", capaciteit: "40 kg", laadhoogte: "-", bedrijfssnelheid: "91-140 RPM", geluidsniveau: "65 dB", veiligheidsvoorzieningen: "Emergency Stop, hinged door with doolock, safe mode", automatisering: "Automatic", gebruikersinterface: "Control panel", connectiviteit: "WiFi", garantie: "1 Jaar", testmodel: false, afbeelding: "https://s3-eu-west-1.amazonaws.com/devchameleon/web-product/68b0008cc837d.png", documentatie: "https://www.chameleon.ie/viewDetails/iMix%20M2M/Gyroscopic_Mixers" },
    { id: 3, naam: "iMix M2M sliding door", fabrikant: "CHAMELEON", type: "MENGER", prijs: null, vermogen: "1.1 kW", spanning: "230 V", frequentie: "50 Hz", afmetingen: "800x860x1100 mm", gewicht: "210 kg", capaciteit: "40 kg", laadhoogte: "-", bedrijfssnelheid: "91-140 RPM", geluidsniveau: "65 dB", veiligheidsvoorzieningen: "Emergency Stop, sliding door with doolock, safe mode", automatisering: "-", gebruikersinterface: "Control panel", connectiviteit: "-", garantie: "1 Jaar", testmodel: false, afbeelding: "https://s3-eu-west-1.amazonaws.com/devchameleon/web-product/61234a5ddae74.png", documentatie: "https://www.chameleon.ie/viewDetails/iMix%20M2M%20Sliding%20Door/Gyroscopic_Mixers" },
    // Shakers
    { id: 4, naam: "iShake PRO", fabrikant: "CHAMELEON", type: "SCHUDDER", prijs: 2889, vermogen: "0.75 kW", spanning: "230 V", frequentie: "50 Hz", afmetingen: "670x720x1170 mm", gewicht: "190 kg", capaciteit: "40 kg", laadhoogte: "490 mm", bedrijfssnelheid: "520-762 RPM", geluidsniveau: "65 dB", veiligheidsvoorzieningen: "Emergency Stop, sliding door with doolock", automatisering: "-", gebruikersinterface: "Control panel/touchscreen", connectiviteit: "WiFi", garantie: "1 Jaar", testmodel: true, afbeelding: "https://s3-eu-west-1.amazonaws.com/devchameleon/web-product/680b4f5a35a51.png", documentatie: "https://www.chameleon.ie/viewDetails/iShake%20PRO/Vibrational_Shakers" },
    { id: 5, naam: "iShake", fabrikant: "CHAMELEON", type: "SCHUDDER", prijs: 2579, vermogen: "0.75 kW", spanning: "230 V", frequentie: "50 Hz", afmetingen: "670x720x1170 mm", gewicht: "190 kg", capaciteit: "40 kg", laadhoogte: "490 mm", bedrijfssnelheid: "520-762 RPM", geluidsniveau: "65 dB", veiligheidsvoorzieningen: "Emergency Stop, hinged door with doolock", automatisering: "-", gebruikersinterface: "Control panel", connectiviteit: "-", garantie: "1 Jaar", testmodel: false, afbeelding: "https://s3-eu-west-1.amazonaws.com/devchameleon/web-product/61234b005d204.png", documentatie: "https://www.chameleon.ie/viewDetails/iShake/Vibrational_Shakers" },
    { id: 6, naam: "iShake M2M ? 2025", fabrikant: "CHAMELEON", type: "SCHUDDER", prijs: null, vermogen: "-", spanning: "-", frequentie: "-", afmetingen: "-", gewicht: "-", capaciteit: "-", laadhoogte: "-", bedrijfssnelheid: "-", geluidsniveau: "-", veiligheidsvoorzieningen: "-", automatisering: "-", gebruikersinterface: "-", connectiviteit: "-", garantie: "1 Jaar", testmodel: false, afbeelding: "https://s3-eu-west-1.amazonaws.com/devchameleon/web-product/6144766a61674.png", documentatie: "https://www.chameleon.ie/viewDetails/iShake%20M2M/Vibrational_Shakers" },
    { id: 7, naam: "eShake", fabrikant: "CHAMELEON", type: "SCHUDDER", prijs: null, vermogen: "0.75 kW", spanning: "230 V", frequentie: "50 Hz", afmetingen: "670x720x1170 mm", gewicht: "190 kg", capaciteit: "40 kg", laadhoogte: "490 mm", bedrijfssnelheid: "-", geluidsniveau: "65 dB", veiligheidsvoorzieningen: "Emergency Stop, hinged door with doolock", automatisering: "Automatic", gebruikersinterface: "buttons", connectiviteit: "-", garantie: "1 Jaar", testmodel: false, afbeelding: "https://s3-eu-west-1.amazonaws.com/devchameleon/web-product/61234d9487b97.png", documentatie: "https://www.chameleon.ie/viewDetails/eShake/Vibrational_Shakers" },

    // === COLLOMIX ===
    // Shakers
    { id: 8, naam: "Viro Neo", fabrikant: "COLLOMIX", type: "SCHUDDER", prijs: 3225, vermogen: "0.9 kW", spanning: "230 V", frequentie: "50 Hz", afmetingen: "675x542x1169 mm", gewicht: "115 kg", capaciteit: "35 kg", laadhoogte: "495 mm", bedrijfssnelheid: "660 RPM", geluidsniveau: "74.2 dB", schudrichting: "monodirectional", veiligheidsvoorzieningen: "Emergency Stop, hinged door with doolock", automatisering: "automatic", gebruikersinterface: "control panel", connectiviteit: "smart CONNECT", garantie: "1 Jaar", testmodel: true, afbeelding: "https://www.collomix.com/01%20Bilder/Produktbilder/colorTEC/Shaker/VIRO/5429/image-thumb__5429__product-gallery-image/PB_VIROneo.jpg", documentatie: "https://www.collomix.com/03%20Dokumente-Variants%20.colorTEC/Datenbl%C3%A4tter%20%26%20Flyer-Produktbrosch%C3%BCre/Shaker/VIROneo/DB_VIRO%20neo_EN_ebook.pdf" },
    { id: 9, naam: "Viba X.30", fabrikant: "COLLOMIX", type: "SCHUDDER", prijs: 4450, vermogen: "0.9 kW", spanning: "230 V", frequentie: "50 Hz", afmetingen: "735x590x1208 mm", gewicht: "130 kg", capaciteit: "40 kg", laadhoogte: "497 mm", bedrijfssnelheid: "660 RPM", geluidsniveau: "74.2 dB", schudrichting: "monodirectional", veiligheidsvoorzieningen: "Emergency Stop, automatic open sliding door", automatisering: "Automatic", gebruikersinterface: "control panel", connectiviteit: "smart CONNECT", garantie: "1 Jaar", testmodel: true, afbeelding: "https://www.collomix.com/01%20Bilder/Produktbilder/colorTEC/Shaker/VIBA/6410/image-thumb__6410__product-gallery-image/PB_Viba_X30_02.png", documentatie: "https://www.collomix.com/03%20Dokumente-Variants%20.colorTEC/Datenbl%C3%A4tter%20%26%20Flyer-Produktbrosch%C3%BCre/Shaker/VIBA/VIBA%20X.30%2C%20X.30%20V/DB_VIBA%20X.30_EN_ebook.pdf" },
    // Mengers
    { id: 10, naam: "Toro Neo", fabrikant: "COLLOMIX", type: "MENGER", prijs: 4250, vermogen: "1.1 kW", spanning: "230 V", frequentie: "50 Hz", afmetingen: "782x811x1007 mm", gewicht: "152 kg", capaciteit: "40 kg", laadhoogte: "385 mm", bedrijfssnelheid: "145 RPM", geluidsniveau: "65 dB", veiligheidsvoorzieningen: "Emergency Stop, hinged door with doolock", automatisering: "Automatic", gebruikersinterface: "control panel", connectiviteit: "smart CONNECT", garantie: "1 Jaar", testmodel: false, afbeelding: "https://www.collomix.com/01%20Bilder/Produktbilder/colorTEC/Biaxialmischer/TORO/5427/image-thumb__5427__product-gallery-image/PB_TORONeo.png", documentatie: "https://www.collomix.com/03%20Dokumente-Variants%20.colorTEC/Datenbl%C3%A4tter%20%26%20Flyer-Produktbrosch%C3%BCre/Biaxialmischer/TORO/TOROneo/DB_TORO%20neo_EN_ebook.pdf" },
    { id: 11, naam: "Rota X.40", fabrikant: "COLLOMIX", type: "MENGER", prijs: 6150, vermogen: "1.1 kW", spanning: "230 V", frequentie: "50 Hz", afmetingen: "796x986x1174 mm", gewicht: "176 kg", capaciteit: "40 kg", laadhoogte: "455 mm", bedrijfssnelheid: "145 RPM", geluidsniveau: "65 dB", schudrichting: "Gyroscopic", veiligheidsvoorzieningen: "Emergency Stop, automatic open sliding door", automatisering: "Automatic", gebruikersinterface: "control panel", connectiviteit: "smart CONNECT", garantie: "1 Jaar", testmodel: true, afbeelding: "https://www.collomix.com/01%20Bilder/Produktbilder/colorTEC/Biaxialmischer/ROTA/6385/image-thumb__6385__product-gallery-image/PB_Rota_X40_02.png", documentatie: "https://www.collomix.com/03%20Dokumente-Variants%20.colorTEC/Datenbl%C3%A4tter%20%26%20Flyer-Produktbrosch%C3%BCre/Biaxialmischer/ROTA/ROTA%20X.40/DB_Rota%20X40_EN_ebook.pdf" },
    { id: 12, naam: "BIAX 35", fabrikant: "COLLOMIX", type: "MENGER", prijs: 6900, vermogen: "1.1 kW", spanning: "230 V", frequentie: "50 Hz", afmetingen: "760x834x1112 mm", gewicht: "209 kg", capaciteit: "40 kg", laadhoogte: "445 mm", bedrijfssnelheid: "160 RPM", geluidsniveau: "64 dB", schudrichting: "Gyroscopic", veiligheidsvoorzieningen: "Emergency Stop, sliding door with doorlock", automatisering: "-", gebruikersinterface: "-", connectiviteit: "-", garantie: "1 Jaar", testmodel: false, afbeelding: "https://www.collomix.com/01%20Bilder/Produktbilder/colorTEC/Biaxialmischer/BIAX/5422/image-thumb__5422__product-gallery-image/PB_BIAX35.jpg", documentatie: "https://www.collomix.com/03%20Dokumente-Variants%20.colorTEC/Datenbl%C3%A4tter%20%26%20Flyer-Produktbrosch%C3%BCre/Biaxialmischer/BIAX/BIAX%2035/DB_BIAX%2035_EN_07117-011_ebook.pdf" },
    { id: 13, naam: "BIAX 45", fabrikant: "COLLOMIX", type: "MENGER", prijs: 9450, vermogen: "1.5 kW", spanning: "230 V", frequentie: "50 Hz", afmetingen: "760x834x1112 mm", gewicht: "209 kg", capaciteit: "50 kg", laadhoogte: "445 mm", bedrijfssnelheid: "160 RPM", geluidsniveau: "64 dB", schudrichting: "Gyroscopic", veiligheidsvoorzieningen: "Emergency Stop, sliding door with doorlock", automatisering: "-", gebruikersinterface: "-", connectiviteit: "-", garantie: "1 Jaar", testmodel: false, afbeelding: "https://www.collomix.com/01%20Bilder/Produktbilder/colorTEC/Biaxialmischer/BIAX/5421/image-thumb__5421__product-gallery-image/PB_BIAX.jpg", documentatie: "https://www.collomix.com/03%20Dokumente-Variants%20.colorTEC/Datenbl%C3%A4tter%20%26%20Flyer-Produktbrosch%C3%BCre/Biaxialmischer/BIAX/BIAX%2045%20P/DB_BIAX%2045%20P_EN_ebook.pdf" },

    // === COROB ===
    // Mengers
    { id: 14, naam: "Clevermix 700E", fabrikant: "COROB", type: "MENGER", prijs: 3995, vermogen: "0.55 kW", spanning: "230 V", frequentie: "50 Hz", afmetingen: "805x782x1112 mm", gewicht: "163 kg", capaciteit: "40 kg", laadhoogte: "-", bedrijfssnelheid: "automatic according to cansize", geluidsniveau: "70 dB", schudrichting: "Bi-directional", veiligheidsvoorzieningen: "Emergency Stop, hinged door with doolock, sliding door or shutter", automatisering: "Automatic", gebruikersinterface: "Control panel", connectiviteit: "usb", garantie: "1 Jaar", testmodel: true, afbeelding: "https://www.corob.com/wp-content/uploads/2023/06/CMIX700-03-T.png", documentatie: "https://www.corob.com/wp-content/download-area/documentation/Brochures/Brochure-CLEVERmix%20700E-v06.pdf" },
    // Shakers
    { id: 15, naam: "Evoshake 200", fabrikant: "COROB", type: "SCHUDDER", prijs: 2790, vermogen: "0.55 kW", spanning: "230 V", frequentie: "50 Hz", afmetingen: "616x602x1132 mm", gewicht: "185 kg", capaciteit: "35 kg", laadhoogte: "415 mm", bedrijfssnelheid: "680 RPM", geluidsniveau: "70 dB", schudrichting: "monodirectional", veiligheidsvoorzieningen: "Emergency Stop, hinged door with doolock", automatisering: "-", gebruikersinterface: "Control panel", connectiviteit: "usb", garantie: "1 Jaar", testmodel: false, afbeelding: "https://www.corob.com/wp-content/uploads/2023/10/Eshake-200-04-T.png", documentatie: "https://www.corob.com/products/mixers-shakers/shakers/evoshake-200" },
    { id: 16, naam: "Evoshake 700", fabrikant: "COROB", type: "SCHUDDER", prijs: 3860, vermogen: "0.55 kW", spanning: "230 V", frequentie: "50 Hz", afmetingen: "616x607x1132 mm", gewicht: "192 kg", capaciteit: "35 kg", laadhoogte: "415 mm", bedrijfssnelheid: "Pre-set or automatically selected Variable customization", geluidsniveau: "70 dB", schudrichting: "Bi-directional", veiligheidsvoorzieningen: "Emergency Stop, hinged door with doolock or sliding door", automatisering: "-", gebruikersinterface: "Control panel", connectiviteit: "usb", garantie: "1 Jaar", testmodel: true, afbeelding: "https://www.corob.com/wp-content/uploads/2023/10/Eshake-700-04-T.png", documentatie: "https://www.corob.com/products/mixers-shakers/shakers/evoshake-700" },

    // === FAST & FLUID ===
    // Mengers
    { id: 17, naam: "GX300", fabrikant: "FAST & FLUID", type: "MENGER", prijs: 3450, vermogen: "0.75 kW", spanning: "230 V", frequentie: "50 Hz", afmetingen: "820x840x1030 mm", gewicht: "215 kg", capaciteit: "40 kg", laadhoogte: "-", bedrijfssnelheid: "80-230 RPM", geluidsniveau: "78 dB", schudrichting: "Gyroscopic", veiligheidsvoorzieningen: "Emergency Stop, hinged door with doolock, table lock", automatisering: "Automatic", gebruikersinterface: "control panel", connectiviteit: "USB Wifi", garantie: "1 Jaar", testmodel: false, afbeelding: "https://fast-fluid.com/emea/wp-content/uploads/sites/3/2025/01/GX300-%E2%80%93-1.jpg", documentatie: "https://fast-fluid.com/emea/products/gx300-automatic-mixer" },
    { id: 18, naam: "GA480", fabrikant: "FAST & FLUID", type: "MENGER", prijs: 4250, vermogen: "0.75 kW", spanning: "230 V", frequentie: "50 Hz", afmetingen: "820x810x1010 mm", gewicht: "240 kg", capaciteit: "40 kg", laadhoogte: "-", bedrijfssnelheid: "90-230 RPM", geluidsniveau: "65 dB", schudrichting: "Gyroscopic", veiligheidsvoorzieningen: "Emergency Stop, hinged door with doolock, table lock", automatisering: "Automatic", gebruikersinterface: "control panel", connectiviteit: "USB Wifi", garantie: "1 Jaar", testmodel: true, afbeelding: "https://fast-fluid.com/emea/wp-content/uploads/sites/3/2024/11/GA480-automatic-mixer-2.jpg", documentatie: "https://fast-fluid.com/emea/products/ga480-automatic-mixer" },
    // Shakers
    { id: 19, naam: "SK350", fabrikant: "FAST & FLUID", type: "SCHUDDER", prijs: 2850, vermogen: "0.75 kW", spanning: "230 V", frequentie: "50 Hz", afmetingen: "610x720x1160 mm", gewicht: "190 kg", capaciteit: "35 kg", laadhoogte: "-", bedrijfssnelheid: "680 RPM", geluidsniveau: "-", schudrichting: "Bi-directional", veiligheidsvoorzieningen: "Emergency Stop, sliding door with doorlock", automatisering: "Automatic", gebruikersinterface: "control panel", connectiviteit: "USB Wifi", garantie: "1 Jaar", testmodel: false, afbeelding: "https://fast-fluid.com/emea/wp-content/uploads/sites/3/2024/11/SK350-paint-shaker.jpg", documentatie: "https://fast-fluid.com/emea/products/sk350-automatic-shaker" },
    { id: 20, naam: "SK550 1.1", fabrikant: "FAST & FLUID", type: "SCHUDDER", prijs: 3950, vermogen: "0.75 kW", spanning: "230 V", frequentie: "50 Hz", afmetingen: "610x720x1160 mm", gewicht: "190 kg", capaciteit: "40 kg", laadhoogte: "-", bedrijfssnelheid: "680 slow start", geluidsniveau: "-", schudrichting: "Bi-directional", veiligheidsvoorzieningen: "Emergency Stop, sliding door with doorlock", automatisering: "Automatic", gebruikersinterface: "control panel", connectiviteit: "USB Wifi", garantie: "1 Jaar", testmodel: true, afbeelding: "https://fast-fluid.com/emea/wp-content/uploads/sites/3/2025/03/SK550-1.1.jpg", documentatie: "https://fast-fluid.com/emea/products/sk550-1-1-automatic-shaker" }
];

// Bereken statistieken
function berekenStatistieken() {
    return {
        totaalMachines: machines.length,
        totaalFabrikanten: [...new Set(machines.map(m => m.fabrikant))].length,
        totaalMengers: machines.filter(m => m.type === 'MENGER').length,
        totaalSchudders: machines.filter(m => m.type === 'SCHUDDER').length
    };
}
